export interface Country {
    name: string;
    code: string;
    flag: string;
    dialCode: string;
    currency: string;
}

export const COUNTRIES: Country[] = [
    { name: 'Sénégal', code: 'SN', flag: '🇸🇳', dialCode: '+221', currency: 'XOF' },
    { name: 'France', code: 'FR', flag: 'ðŸ‡«ðŸ‡·', dialCode: '+33', currency: 'EUR' },
    { name: 'Afghanistan', code: 'AF', flag: 'ðŸ‡¦ðŸ‡«', dialCode: '+93', currency: 'AFN' },
    { name: 'Afrique du Sud', code: 'ZA', flag: 'ðŸ‡¿ðŸ‡¦', dialCode: '+27', currency: 'ZAR' },
    { name: 'Albanie', code: 'AL', flag: 'ðŸ‡¦ðŸ‡±', dialCode: '+355', currency: 'ALL' },
    { name: 'Algérie', code: 'DZ', flag: '🇩🇿', dialCode: '+213', currency: 'DZD' },
    { name: 'Allemagne', code: 'DE', flag: 'ðŸ‡©ðŸ‡ª', dialCode: '+49', currency: 'EUR' },
    { name: 'Andorre', code: 'AD', flag: 'ðŸ‡¦ðŸ‡©', dialCode: '+376', currency: 'EUR' },
    { name: 'Angola', code: 'AO', flag: 'ðŸ‡¦ðŸ‡´', dialCode: '+244', currency: 'AOA' },
    { name: 'Anguilla', code: 'AI', flag: 'ðŸ‡¦ðŸ‡®', dialCode: '+1264', currency: 'XCD' },
    { name: 'Antarctique', code: 'AQ', flag: 'ðŸ‡¦ðŸ‡¶', dialCode: '+672', currency: 'AAD' },
    { name: 'Antigua-et-Barbuda', code: 'AG', flag: 'ðŸ‡¦ðŸ‡¬', dialCode: '+1268', currency: 'XCD' },
    { name: 'Arabie Saoudite', code: 'SA', flag: 'ðŸ‡¸ðŸ‡¦', dialCode: '+966', currency: 'SAR' },
    { name: 'Argentine', code: 'AR', flag: 'ðŸ‡¦ðŸ‡·', dialCode: '+54', currency: 'ARS' },
    { name: 'Arménie', code: 'AM', flag: '🇦🇲', dialCode: '+374', currency: 'AMD' },
    { name: 'Aruba', code: 'AW', flag: 'ðŸ‡¦ðŸ‡¼', dialCode: '+297', currency: 'AWG' },
    { name: 'Australie', code: 'AU', flag: 'ðŸ‡¦ðŸ‡º', dialCode: '+61', currency: 'AUD' },
    { name: 'Autriche', code: 'AT', flag: 'ðŸ‡¦ðŸ‡¹', dialCode: '+43', currency: 'EUR' },
    { name: 'Azerbaïdjan', code: 'AZ', flag: '🇦🇿', dialCode: '+994', currency: 'AZN' },
    { name: 'Bahamas', code: 'BS', flag: 'ðŸ‡§ðŸ‡¸', dialCode: '+1242', currency: 'BSD' },
    { name: 'Bahreïn', code: 'BH', flag: '🇧🇭', dialCode: '+973', currency: 'BHD' },
    { name: 'Bangladesh', code: 'BD', flag: 'ðŸ‡§ðŸ‡©', dialCode: '+880', currency: 'BDT' },
    { name: 'Barbade', code: 'BB', flag: 'ðŸ‡§ðŸ‡§', dialCode: '+1246', currency: 'BBD' },
    { name: 'Belgique', code: 'BE', flag: 'ðŸ‡§ðŸ‡ª', dialCode: '+32', currency: 'EUR' },
    { name: 'Belize', code: 'BZ', flag: 'ðŸ‡§ðŸ‡¿', dialCode: '+501', currency: 'BZD' },
    { name: 'Bénin', code: 'BJ', flag: '🇧🇯', dialCode: '+229', currency: 'XOF' },
    { name: 'Bermudes', code: 'BM', flag: 'ðŸ‡§ðŸ‡²', dialCode: '+1441', currency: 'BMD' },
    { name: 'Bhoutan', code: 'BT', flag: 'ðŸ‡§ðŸ‡¹', dialCode: '+975', currency: 'BTN' },
    { name: 'Biélorussie', code: 'BY', flag: '🇧🇾', dialCode: '+375', currency: 'BYR' },
    { name: 'Bolivie', code: 'BO', flag: 'ðŸ‡§ðŸ‡´', dialCode: '+591', currency: 'BOB' },
    { name: 'Bosnie-Herzégovine', code: 'BA', flag: '🇧🇦', dialCode: '+387', currency: 'BAM' },
    { name: 'Botswana', code: 'BW', flag: 'ðŸ‡§ðŸ‡¼', dialCode: '+267', currency: 'BWP' },
    { name: 'Brésil', code: 'BR', flag: '🇧🇷', dialCode: '+55', currency: 'BRL' },
    { name: 'Brunei', code: 'BN', flag: 'ðŸ‡§ðŸ‡³', dialCode: '+673', currency: 'BND' },
    { name: 'Bulgarie', code: 'BG', flag: 'ðŸ‡§ðŸ‡¬', dialCode: '+359', currency: 'BGN' },
    { name: 'Burkina Faso', code: 'BF', flag: 'ðŸ‡§ðŸ‡«', dialCode: '+226', currency: 'XOF' },
    { name: 'Burundi', code: 'BI', flag: 'ðŸ‡§ðŸ‡®', dialCode: '+257', currency: 'BIF' },
    { name: 'Cambodge', code: 'KH', flag: 'ðŸ‡°ðŸ‡­', dialCode: '+855', currency: 'KHR' },
    { name: 'Cameroun', code: 'CM', flag: 'ðŸ‡¨ðŸ‡²', dialCode: '+237', currency: 'XAF' },
    { name: 'Canada', code: 'CA', flag: 'ðŸ‡¨ðŸ‡¦', dialCode: '+1', currency: 'CAD' },
    { name: 'Cap-Vert', code: 'CV', flag: 'ðŸ‡¨ðŸ‡»', dialCode: '+238', currency: 'CVE' },
    { name: 'Chili', code: 'CL', flag: 'ðŸ‡¨ðŸ‡±', dialCode: '+56', currency: 'CLP' },
    { name: 'Chine', code: 'CN', flag: 'ðŸ‡¨ðŸ‡³', dialCode: '+86', currency: 'CNY' },
    { name: 'Chypre', code: 'CY', flag: 'ðŸ‡¨ðŸ‡¾', dialCode: '+357', currency: 'EUR' },
    { name: 'Colombie', code: 'CO', flag: 'ðŸ‡¨ðŸ‡´', dialCode: '+57', currency: 'COP' },
    { name: 'Comores', code: 'KM', flag: 'ðŸ‡°ðŸ‡²', dialCode: '+269', currency: 'KMF' },
    { name: 'Congo-Brazzaville', code: 'CG', flag: 'ðŸ‡¨ðŸ‡¬', dialCode: '+242', currency: 'XAF' },
    { name: 'Congo-Kinshasa', code: 'CD', flag: 'ðŸ‡¨ðŸ‡©', dialCode: '+243', currency: 'CDF' },
    { name: 'Corée du Nord', code: 'KP', flag: '🇰🇵', dialCode: '+850', currency: 'KPW' },
    { name: 'Corée du Sud', code: 'KR', flag: '🇰🇷', dialCode: '+82', currency: 'KRW' },
    { name: 'Costa Rica', code: 'CR', flag: 'ðŸ‡¨ðŸ‡·', dialCode: '+506', currency: 'CRC' },
    { name: 'Côte d\u2019Ivoire', code: 'CI', flag: '🇨🇮', dialCode: '+225', currency: 'XOF' },
    { name: 'Croatie', code: 'HR', flag: 'ðŸ‡­ðŸ‡·', dialCode: '+385', currency: 'HRK' },
    { name: 'Cuba', code: 'CU', flag: 'ðŸ‡¨ðŸ‡º', dialCode: '+53', currency: 'CUP' },
    { name: 'Danemark', code: 'DK', flag: 'ðŸ‡©ðŸ‡°', dialCode: '+45', currency: 'DKK' },
    { name: 'Djibouti', code: 'DJ', flag: 'ðŸ‡©ðŸ‡¯', dialCode: '+253', currency: 'DJF' },
    { name: 'Dominique', code: 'DM', flag: 'ðŸ‡©ðŸ‡²', dialCode: '+1767', currency: 'XCD' },
    { name: 'Égypte', code: 'EG', flag: '🇪🇬', dialCode: '+20', currency: 'EGP' },
    { name: 'Émirats Arabes Unis', code: 'AE', flag: '🇦🇪', dialCode: '+971', currency: 'AED' },
    { name: 'Équateur', code: 'EC', flag: '🇪🇨', dialCode: '+593', currency: 'USD' },
    { name: 'Érythrée', code: 'ER', flag: '🇪🇷', dialCode: '+291', currency: 'ERN' },
    { name: 'Espagne', code: 'ES', flag: 'ðŸ‡ªðŸ‡¸', dialCode: '+34', currency: 'EUR' },
    { name: 'Estonie', code: 'EE', flag: 'ðŸ‡ªðŸ‡ª', dialCode: '+372', currency: 'EUR' },
    { name: 'Eswatini', code: 'SZ', flag: 'ðŸ‡¸ðŸ‡¿', dialCode: '+268', currency: 'SZL' },
    { name: 'États-Unis', code: 'US', flag: '🇺🇸', dialCode: '+1', currency: 'USD' },
    { name: 'Éthiopie', code: 'ET', flag: '🇪🇹', dialCode: '+251', currency: 'ETB' },
    { name: 'Fidji', code: 'FJ', flag: 'ðŸ‡«ðŸ‡¯', dialCode: '+679', currency: 'FJD' },
    { name: 'Finlande', code: 'FI', flag: 'ðŸ‡«ðŸ‡®', dialCode: '+358', currency: 'EUR' },
    { name: 'Gabon', code: 'GA', flag: 'ðŸ‡¬ðŸ‡¦', dialCode: '+241', currency: 'XAF' },
    { name: 'Gambie', code: 'GM', flag: 'ðŸ‡¬ðŸ‡²', dialCode: '+220', currency: 'GMD' },
    { name: 'Géorgie', code: 'GE', flag: '🇬🇪', dialCode: '+995', currency: 'GEL' },
    { name: 'Ghana', code: 'GH', flag: 'ðŸ‡¬ðŸ‡­', dialCode: '+233', currency: 'GHS' },
    { name: 'Gibraltar', code: 'GI', flag: 'ðŸ‡¬ðŸ‡®', dialCode: '+350', currency: 'GIP' },
    { name: 'Grèce', code: 'GR', flag: '🇬🇷', dialCode: '+30', currency: 'EUR' },
    { name: 'Grenade', code: 'GD', flag: 'ðŸ‡¬ðŸ‡©', dialCode: '+1473', currency: 'XCD' },
    { name: 'Groenland', code: 'GL', flag: 'ðŸ‡¬ðŸ‡±', dialCode: '+299', currency: 'DKK' },
    { name: 'Guadeloupe', code: 'GP', flag: 'ðŸ‡¬ðŸ‡µ', dialCode: '+590', currency: 'EUR' },
    { name: 'Guam', code: 'GU', flag: 'ðŸ‡¬ðŸ‡º', dialCode: '+1671', currency: 'USD' },
    { name: 'Guatemala', code: 'GT', flag: 'ðŸ‡¬ðŸ‡¹', dialCode: '+502', currency: 'GTQ' },
    { name: 'Guernesey', code: 'GG', flag: 'ðŸ‡¬ðŸ‡¬', dialCode: '+44', currency: 'GGP' },
    { name: 'Guinée', code: 'GN', flag: '🇬🇳', dialCode: '+224', currency: 'GNF' },
    { name: 'Guinée-Bissau', code: 'GW', flag: '🇬🇼', dialCode: '+245', currency: 'XOF' },
    { name: 'Guinée Équatoriale', code: 'GQ', flag: '🇬🇶', dialCode: '+240', currency: 'XAF' },
    { name: 'Guyana', code: 'GY', flag: 'ðŸ‡¬ðŸ‡¾', dialCode: '+592', currency: 'GYD' },
    { name: 'Guyane française', code: 'GF', flag: '🇬🇫', dialCode: '+594', currency: 'EUR' },
    { name: 'Haïti', code: 'HT', flag: '🇭🇹', dialCode: '+509', currency: 'HTG' },
    { name: 'Honduras', code: 'HN', flag: 'ðŸ‡­ðŸ‡³', dialCode: '+504', currency: 'HNL' },
    { name: 'Hong Kong', code: 'HK', flag: 'ðŸ‡­ðŸ‡°', dialCode: '+852', currency: 'HKD' },
    { name: 'Hongrie', code: 'HU', flag: 'ðŸ‡­ðŸ‡º', dialCode: '+36', currency: 'HUF' },
    { name: 'Île de Man', code: 'IM', flag: '🇮🇲', dialCode: '+44', currency: 'IMP' },
    { name: 'Île Maurice', code: 'MU', flag: '🇲🇺', dialCode: '+230', currency: 'MUR' },
    { name: 'Îles Caïmans', code: 'KY', flag: '🇰🇾', dialCode: '+1345', currency: 'KYD' },
    { name: 'Îles Cook', code: 'CK', flag: '🇨🇰', dialCode: '+682', currency: 'NZD' },
    { name: 'Îles Féroé', code: 'FO', flag: '🇫🇴', dialCode: '+298', currency: 'DKK' },
    { name: 'Îles Malouines', code: 'FK', flag: '🇫🇰', dialCode: '+500', currency: 'FKP' },
    { name: 'Îles Marshall', code: 'MH', flag: '🇲🇭', dialCode: '+692', currency: 'USD' },
    { name: 'Îles Salomon', code: 'SB', flag: '🇸🇧', dialCode: '+677', currency: 'SBD' },
    { name: 'Îles Turques-et-Caïques', code: 'TC', flag: '🇹🇨', dialCode: '+1649', currency: 'USD' },
    { name: 'Îles Vierges britanniques', code: 'VG', flag: '🇻🇬', dialCode: '+1284', currency: 'USD' },
    { name: 'Îles Vierges des États-Unis', code: 'VI', flag: '🇻🇮', dialCode: '+1340', currency: 'USD' },
    { name: 'Inde', code: 'IN', flag: 'ðŸ‡®ðŸ‡³', dialCode: '+91', currency: 'INR' },
    { name: 'Indonésie', code: 'ID', flag: '🇮🇩', dialCode: '+62', currency: 'IDR' },
    { name: 'Irak', code: 'IQ', flag: 'ðŸ‡®ðŸ‡¶', dialCode: '+964', currency: 'IQD' },
    { name: 'Iran', code: 'IR', flag: 'ðŸ‡®ðŸ‡·', dialCode: '+98', currency: 'IRR' },
    { name: 'Irlande', code: 'IE', flag: 'ðŸ‡®ðŸ‡ª', dialCode: '+353', currency: 'EUR' },
    { name: 'Islande', code: 'IS', flag: 'ðŸ‡®ðŸ‡¸', dialCode: '+354', currency: 'ISK' },
    { name: 'Israël', code: 'IL', flag: '🇮🇱', dialCode: '+972', currency: 'ILS' },
    { name: 'Italie', code: 'IT', flag: 'ðŸ‡®ðŸ‡¹', dialCode: '+39', currency: 'EUR' },
    { name: 'Jamaïque', code: 'JM', flag: '🇯🇲', dialCode: '+1876', currency: 'JMD' },
    { name: 'Japon', code: 'JP', flag: 'ðŸ‡¯ðŸ‡µ', dialCode: '+81', currency: 'JPY' },
    { name: 'Jersey', code: 'JE', flag: 'ðŸ‡¯ðŸ‡ª', dialCode: '+44', currency: 'JEP' },
    { name: 'Jordanie', code: 'JO', flag: 'ðŸ‡¯ðŸ‡´', dialCode: '+962', currency: 'JOD' },
    { name: 'Kazakhstan', code: 'KZ', flag: 'ðŸ‡°ðŸ‡¿', dialCode: '+7', currency: 'KZT' },
    { name: 'Kenya', code: 'KE', flag: 'ðŸ‡°ðŸ‡ª', dialCode: '+254', currency: 'KES' },
    { name: 'Kirghizistan', code: 'KG', flag: 'ðŸ‡°ðŸ‡¬', dialCode: '+996', currency: 'KGS' },
    { name: 'Kiribati', code: 'KI', flag: 'ðŸ‡°ðŸ‡®', dialCode: '+686', currency: 'AUD' },
    { name: 'Koweït', code: 'KW', flag: '🇰🇼', dialCode: '+965', currency: 'KWD' },
    { name: 'Laos', code: 'LA', flag: 'ðŸ‡±ðŸ‡¦', dialCode: '+856', currency: 'LAK' },
    { name: 'Lesotho', code: 'LS', flag: 'ðŸ‡±ðŸ‡¸', dialCode: '+266', currency: 'LSL' },
    { name: 'Lettonie', code: 'LV', flag: 'ðŸ‡±ðŸ‡»', dialCode: '+371', currency: 'EUR' },
    { name: 'Liban', code: 'LB', flag: 'ðŸ‡±ðŸ‡§', dialCode: '+961', currency: 'LBP' },
    { name: 'Libéria', code: 'LR', flag: '🇱🇷', dialCode: '+231', currency: 'LRD' },
    { name: 'Libye', code: 'LY', flag: 'ðŸ‡±ðŸ‡¾', dialCode: '+218', currency: 'LYD' },
    { name: 'Liechtenstein', code: 'LI', flag: 'ðŸ‡±ðŸ‡®', dialCode: '+423', currency: 'CHF' },
    { name: 'Lituanie', code: 'LT', flag: 'ðŸ‡±ðŸ‡¹', dialCode: '+370', currency: 'EUR' },
    { name: 'Luxembourg', code: 'LU', flag: 'ðŸ‡±ðŸ‡º', dialCode: '+352', currency: 'EUR' },
    { name: 'Macao', code: 'MO', flag: 'ðŸ‡²ðŸ‡´', dialCode: '+853', currency: 'MOP' },
    { name: 'Macédoine du Nord', code: 'MK', flag: '🇲🇰', dialCode: '+389', currency: 'MKD' },
    { name: 'Madagascar', code: 'MG', flag: 'ðŸ‡²ðŸ‡¬', dialCode: '+261', currency: 'MGA' },
    { name: 'Malaisie', code: 'MY', flag: 'ðŸ‡²ðŸ‡¾', dialCode: '+60', currency: 'MYR' },
    { name: 'Malawi', code: 'MW', flag: 'ðŸ‡²ðŸ‡¼', dialCode: '+265', currency: 'MWK' },
    { name: 'Maldives', code: 'MV', flag: 'ðŸ‡²ðŸ‡»', dialCode: '+960', currency: 'MVR' },
    { name: 'Mali', code: 'ML', flag: 'ðŸ‡²ðŸ‡±', dialCode: '+223', currency: 'XOF' },
    { name: 'Malte', code: 'MT', flag: 'ðŸ‡²ðŸ‡¹', dialCode: '+356', currency: 'EUR' },
    { name: 'Mariannes du Nord', code: 'MP', flag: 'ðŸ‡²ðŸ‡µ', dialCode: '+1670', currency: 'USD' },
    { name: 'Maroc', code: 'MA', flag: 'ðŸ‡²ðŸ‡¦', dialCode: '+212', currency: 'MAD' },
    { name: 'Martinique', code: 'MQ', flag: 'ðŸ‡²ðŸ‡¶', dialCode: '+596', currency: 'EUR' },
    { name: 'Maurice', code: 'MU', flag: 'ðŸ‡²ðŸ‡º', dialCode: '+230', currency: 'MUR' },
    { name: 'Mauritanie', code: 'MR', flag: 'ðŸ‡²ðŸ‡·', dialCode: '+222', currency: 'MRU' },
    { name: 'Mayotte', code: 'YT', flag: 'ðŸ‡¾ðŸ‡¹', dialCode: '+262', currency: 'EUR' },
    { name: 'Mexique', code: 'MX', flag: 'ðŸ‡²ðŸ‡½', dialCode: '+52', currency: 'MXN' },
    { name: 'Micronésie', code: 'FM', flag: '🇫🇲', dialCode: '+691', currency: 'USD' },
    { name: 'Moldavie', code: 'MD', flag: 'ðŸ‡²ðŸ‡©', dialCode: '+373', currency: 'MDL' },
    { name: 'Monaco', code: 'MC', flag: 'ðŸ‡²ðŸ‡¨', dialCode: '+377', currency: 'EUR' },
    { name: 'Mongolie', code: 'MN', flag: 'ðŸ‡²ðŸ‡³', dialCode: '+976', currency: 'MNT' },
    { name: 'Monténégro', code: 'ME', flag: '🇲🇪', dialCode: '+382', currency: 'EUR' },
    { name: 'Montserrat', code: 'MS', flag: 'ðŸ‡²ðŸ‡¸', dialCode: '+1664', currency: 'XCD' },
    { name: 'Mozambique', code: 'MZ', flag: 'ðŸ‡²ðŸ‡¿', dialCode: '+258', currency: 'MZN' },
    { name: 'Myanmar', code: 'MM', flag: 'ðŸ‡²ðŸ‡²', dialCode: '+95', currency: 'MMK' },
    { name: 'Namibie', code: 'NA', flag: 'ðŸ‡³ðŸ‡¦', dialCode: '+264', currency: 'NAD' },
    { name: 'Nauru', code: 'NR', flag: 'ðŸ‡³ðŸ‡·', dialCode: '+674', currency: 'AUD' },
    { name: 'Népal', code: 'NP', flag: '🇳🇵', dialCode: '+977', currency: 'NPR' },
    { name: 'Nicaragua', code: 'NI', flag: 'ðŸ‡³ðŸ‡®', dialCode: '+505', currency: 'NIO' },
    { name: 'Niger', code: 'NE', flag: 'ðŸ‡³ðŸ‡ª', dialCode: '+227', currency: 'XOF' },
    { name: 'Nigeria', code: 'NG', flag: 'ðŸ‡³ðŸ‡¬', dialCode: '+234', currency: 'NGN' },
    { name: 'Niue', code: 'NU', flag: 'ðŸ‡³ðŸ‡º', dialCode: '+683', currency: 'NZD' },
    { name: 'Norvège', code: 'NO', flag: '🇳🇴', dialCode: '+47', currency: 'NOK' },
    { name: 'Nouvelle-Calédonie', code: 'NC', flag: '🇳🇨', dialCode: '+687', currency: 'XPF' },
    { name: 'Nouvelle-Zélande', code: 'NZ', flag: '🇳🇿', dialCode: '+64', currency: 'NZD' },
    { name: 'Oman', code: 'OM', flag: 'ðŸ‡´ðŸ‡²', dialCode: '+968', currency: 'OMR' },
    { name: 'Ouganda', code: 'UG', flag: 'ðŸ‡ºðŸ‡¬', dialCode: '+256', currency: 'UGX' },
    { name: 'Ouzbékistan', code: 'UZ', flag: '🇺🇿', dialCode: '+998', currency: 'UZS' },
    { name: 'Pakistan', code: 'PK', flag: 'ðŸ‡µðŸ‡°', dialCode: '+92', currency: 'PKR' },
    { name: 'Palaos', code: 'PW', flag: 'ðŸ‡µðŸ‡¼', dialCode: '+680', currency: 'USD' },
    { name: 'Palestine', code: 'PS', flag: 'ðŸ‡µðŸ‡¸', dialCode: '+970', currency: 'ILS' },
    { name: 'Panama', code: 'PA', flag: 'ðŸ‡µðŸ‡¦', dialCode: '+507', currency: 'PAB' },
    { name: 'Papouasie-Nouvelle-Guinée', code: 'PG', flag: '🇵🇬', dialCode: '+675', currency: 'PGK' },
    { name: 'Paraguay', code: 'PY', flag: 'ðŸ‡µðŸ‡¾', dialCode: '+595', currency: 'PYG' },
    { name: 'Pays-Bas', code: 'NL', flag: 'ðŸ‡³ðŸ‡±', dialCode: '+31', currency: 'EUR' },
    { name: 'Pérou', code: 'PE', flag: '🇵🇪', dialCode: '+51', currency: 'PEN' },
    { name: 'Philippines', code: 'PH', flag: 'ðŸ‡µðŸ‡­', dialCode: '+63', currency: 'PHP' },
    { name: 'Pologne', code: 'PL', flag: 'ðŸ‡µðŸ‡±', dialCode: '+48', currency: 'PLN' },
    { name: 'Polynésie française', code: 'PF', flag: '🇵🇫', dialCode: '+689', currency: 'XPF' },
    { name: 'Porto Rico', code: 'PR', flag: 'ðŸ‡µðŸ‡·', dialCode: '+1787', currency: 'USD' },
    { name: 'Portugal', code: 'PT', flag: 'ðŸ‡µðŸ‡¹', dialCode: '+351', currency: 'EUR' },
    { name: 'Qatar', code: 'QA', flag: 'ðŸ‡¶ðŸ‡¦', dialCode: '+974', currency: 'QAR' },
    { name: 'RCA', code: 'CF', flag: 'ðŸ‡¨ðŸ‡«', dialCode: '+236', currency: 'XAF' },
    { name: 'Réunion', code: 'RE', flag: '🇷🇪', dialCode: '+262', currency: 'EUR' },
    { name: 'Roumanie', code: 'RO', flag: 'ðŸ‡·ðŸ‡´', dialCode: '+40', currency: 'RON' },
    { name: 'Royaume-Uni', code: 'GB', flag: 'ðŸ‡¬ðŸ‡§', dialCode: '+44', currency: 'GBP' },
    { name: 'Russie', code: 'RU', flag: 'ðŸ‡·ðŸ‡º', dialCode: '+7', currency: 'RUB' },
    { name: 'Rwanda', code: 'RW', flag: 'ðŸ‡·ðŸ‡¼', dialCode: '+250', currency: 'RWF' },
    { name: 'Sahara occidental', code: 'EH', flag: 'ðŸ‡ªðŸ‡­', dialCode: '+212', currency: 'MAD' },
    { name: 'Saint-Barthélemy', code: 'BL', flag: '🇧🇱', dialCode: '+590', currency: 'EUR' },
    { name: 'Saint-Christophe-et-Niévès', code: 'KN', flag: '🇰🇳', dialCode: '+1869', currency: 'XCD' },
    { name: 'Saint-Marin', code: 'SM', flag: 'ðŸ‡¸ðŸ‡²', dialCode: '+378', currency: 'EUR' },
    { name: 'Saint-Martin', code: 'MF', flag: 'ðŸ‡²ðŸ‡«', dialCode: '+590', currency: 'EUR' },
    { name: 'Saint-Pierre-et-Miquelon', code: 'PM', flag: 'ðŸ‡µðŸ‡²', dialCode: '+508', currency: 'EUR' },
    { name: 'Saint-Vincent-et-les-Grenadines', code: 'VC', flag: 'ðŸ‡»ðŸ‡¨', dialCode: '+1784', currency: 'XCD' },
    { name: 'Sainte-Hélène', code: 'SH', flag: '🇸🇭', dialCode: '+290', currency: 'SHP' },
    { name: 'Sainte-Lucie', code: 'LC', flag: 'ðŸ‡±ðŸ‡¨', dialCode: '+1758', currency: 'XCD' },
    { name: 'Salvador', code: 'SV', flag: 'ðŸ‡¸ðŸ‡»', dialCode: '+503', currency: 'USD' },
    { name: 'Samoa', code: 'WS', flag: 'ðŸ‡¼ðŸ‡¸', dialCode: '+685', currency: 'WST' },
    { name: 'Samoa américaines', code: 'AS', flag: '🇦🇸', dialCode: '+1684', currency: 'USD' },
    { name: 'Sao Tomé-et-Principe', code: 'ST', flag: '🇸🇹', dialCode: '+239', currency: 'STD' },
    { name: 'Serbie', code: 'RS', flag: 'ðŸ‡·ðŸ‡¸', dialCode: '+381', currency: 'RSD' },
    { name: 'Seychelles', code: 'SC', flag: 'ðŸ‡¸ðŸ‡¨', dialCode: '+248', currency: 'SCR' },
    { name: 'Sierra Leone', code: 'SL', flag: 'ðŸ‡¸ðŸ‡±', dialCode: '+232', currency: 'SLL' },
    { name: 'Singapour', code: 'SG', flag: 'ðŸ‡¸ðŸ‡¬', dialCode: '+65', currency: 'SGD' },
    { name: 'Slovaquie', code: 'SK', flag: 'ðŸ‡¸ðŸ‡°', dialCode: '+421', currency: 'EUR' },
    { name: 'Slovénie', code: 'SI', flag: '🇸🇮', dialCode: '+386', currency: 'EUR' },
    { name: 'Somalie', code: 'SO', flag: 'ðŸ‡¸ðŸ‡´', dialCode: '+252', currency: 'SOS' },
    { name: 'Soudan', code: 'SD', flag: 'ðŸ‡¸ðŸ‡©', dialCode: '+249', currency: 'SDG' },
    { name: 'Soudan du Sud', code: 'SS', flag: 'ðŸ‡¸ðŸ‡¸', dialCode: '+211', currency: 'SSP' },
    { name: 'Sri Lanka', code: 'LK', flag: 'ðŸ‡±ðŸ‡°', dialCode: '+94', currency: 'LKR' },
    { name: 'Suède', code: 'SE', flag: '🇸🇪', dialCode: '+46', currency: 'SEK' },
    { name: 'Suisse', code: 'CH', flag: 'ðŸ‡¨ðŸ‡­', dialCode: '+41', currency: 'CHF' },
    { name: 'Suriname', code: 'SR', flag: 'ðŸ‡¸ðŸ‡·', dialCode: '+597', currency: 'SRD' },
    { name: 'Syrie', code: 'SY', flag: 'ðŸ‡¸ðŸ‡¾', dialCode: '+963', currency: 'SYP' },
    { name: 'Tadjikistan', code: 'TJ', flag: 'ðŸ‡¹ðŸ‡¯', dialCode: '+992', currency: 'TJS' },
    { name: 'Taïwan', code: 'TW', flag: '🇹🇼', dialCode: '+886', currency: 'TWD' },
    { name: 'Tanzanie', code: 'TZ', flag: 'ðŸ‡¹ðŸ‡¿', dialCode: '+255', currency: 'TZS' },
    { name: 'Tchad', code: 'TD', flag: 'ðŸ‡¹ðŸ‡©', dialCode: '+235', currency: 'XAF' },
    { name: 'Tchéquie', code: 'CZ', flag: '🇨🇿', dialCode: '+420', currency: 'CZK' },
    { name: 'Terres australes françaises', code: 'TF', flag: '🇹🇫', dialCode: '+262', currency: 'EUR' },
    { name: 'Thaïlande', code: 'TH', flag: '🇹🇭', dialCode: '+66', currency: 'THB' },
    { name: 'Timor oriental', code: 'TL', flag: 'ðŸ‡¹ðŸ‡±', dialCode: '+670', currency: 'USD' },
    { name: 'Togo', code: 'TG', flag: 'ðŸ‡¹ðŸ‡¬', dialCode: '+228', currency: 'XOF' },
    { name: 'Tokelau', code: 'TK', flag: 'ðŸ‡¹ðŸ‡°', dialCode: '+690', currency: 'NZD' },
    { name: 'Tonga', code: 'TO', flag: 'ðŸ‡¹ðŸ‡´', dialCode: '+676', currency: 'TOP' },
    { name: 'Trinité-et-Tobago', code: 'TT', flag: '🇹🇹', dialCode: '+1868', currency: 'TTD' },
    { name: 'Tunisie', code: 'TN', flag: 'ðŸ‡¹ðŸ‡³', dialCode: '+216', currency: 'TND' },
    { name: 'Turkménistan', code: 'TM', flag: '🇹🇲', dialCode: '+993', currency: 'TMT' },
    { name: 'Turquie', code: 'TR', flag: 'ðŸ‡¹ðŸ‡·', dialCode: '+90', currency: 'TRY' },
    { name: 'Tuvalu', code: 'TV', flag: 'ðŸ‡¹ðŸ‡»', dialCode: '+688', currency: 'AUD' },
    { name: 'Ukraine', code: 'UA', flag: 'ðŸ‡ºðŸ‡¦', dialCode: '+380', currency: 'UAH' },
    { name: 'Uruguay', code: 'UY', flag: 'ðŸ‡ºðŸ‡¾', dialCode: '+598', currency: 'UYU' },
    { name: 'Vanuatu', code: 'VU', flag: 'ðŸ‡»ðŸ‡º', dialCode: '+678', currency: 'VUV' },
    { name: 'Vatican', code: 'VA', flag: 'ðŸ‡»ðŸ‡¦', dialCode: '+39', currency: 'EUR' },
    { name: 'Venezuela', code: 'VE', flag: 'ðŸ‡»ðŸ‡ª', dialCode: '+58', currency: 'VEF' },
    { name: 'Viêt Nam', code: 'VN', flag: '🇻🇳', dialCode: '+84', currency: 'VND' },
    { name: 'Wallis-et-Futuna', code: 'WF', flag: 'ðŸ‡¼ðŸ‡«', dialCode: '+681', currency: 'XPF' },
    { name: 'Yémen', code: 'YE', flag: '🇾🇪', dialCode: '+967', currency: 'YER' },
    { name: 'Zambie', code: 'ZM', flag: 'ðŸ‡¿ðŸ‡²', dialCode: '+260', currency: 'ZMK' },
    { name: 'Zimbabwe', code: 'ZW', flag: 'ðŸ‡¿ðŸ‡¼', dialCode: '+263', currency: 'ZWL' },
];
