export interface Country {
    name: string;
    code: string;
    flag: string;
    dialCode: string;
    currency: string;
}

export const COUNTRIES: Country[] = [
    { name: 'Sénégal', code: 'SN', flag: '🇸🇳', dialCode: '+221', currency: 'XOF' },
    { name: 'France', code: 'FR', flag: '🇫🇷', dialCode: '+33', currency: 'EUR' },
    { name: 'Afghanistan', code: 'AF', flag: '🇦🇫', dialCode: '+93', currency: 'AFN' },
    { name: 'Afrique du Sud', code: 'ZA', flag: '🇿🇦', dialCode: '+27', currency: 'ZAR' },
    { name: 'Albanie', code: 'AL', flag: '🇦🇱', dialCode: '+355', currency: 'ALL' },
    { name: 'Algérie', code: 'DZ', flag: '🇩🇿', dialCode: '+213', currency: 'DZD' },
    { name: 'Allemagne', code: 'DE', flag: '🇩🇪', dialCode: '+49', currency: 'EUR' },
    { name: 'Andorre', code: 'AD', flag: '🇦🇩', dialCode: '+376', currency: 'EUR' },
    { name: 'Angola', code: 'AO', flag: '🇦🇴', dialCode: '+244', currency: 'AOA' },
    { name: 'Anguilla', code: 'AI', flag: '🇦🇮', dialCode: '+1264', currency: 'XCD' },
    { name: 'Antarctique', code: 'AQ', flag: '🇦🇶', dialCode: '+672', currency: 'AAD' },
    { name: 'Antigua-et-Barbuda', code: 'AG', flag: '🇦🇬', dialCode: '+1268', currency: 'XCD' },
    { name: 'Arabie Saoudite', code: 'SA', flag: '🇸🇦', dialCode: '+966', currency: 'SAR' },
    { name: 'Argentine', code: 'AR', flag: '🇦🇷', dialCode: '+54', currency: 'ARS' },
    { name: 'Arménie', code: 'AM', flag: '🇦🇲', dialCode: '+374', currency: 'AMD' },
    { name: 'Aruba', code: 'AW', flag: '🇦🇼', dialCode: '+297', currency: 'AWG' },
    { name: 'Australie', code: 'AU', flag: '🇦🇺', dialCode: '+61', currency: 'AUD' },
    { name: 'Autriche', code: 'AT', flag: '🇦🇹', dialCode: '+43', currency: 'EUR' },
    { name: 'Azerbaïdjan', code: 'AZ', flag: '🇦🇿', dialCode: '+994', currency: 'AZN' },
    { name: 'Bahamas', code: 'BS', flag: '🇧🇸', dialCode: '+1242', currency: 'BSD' },
    { name: 'Bahreïn', code: 'BH', flag: '🇧🇭', dialCode: '+973', currency: 'BHD' },
    { name: 'Bangladesh', code: 'BD', flag: '🇧🇩', dialCode: '+880', currency: 'BDT' },
    { name: 'Barbade', code: 'BB', flag: '🇧🇧', dialCode: '+1246', currency: 'BBD' },
    { name: 'Belgique', code: 'BE', flag: '🇧🇪', dialCode: '+32', currency: 'EUR' },
    { name: 'Belize', code: 'BZ', flag: '🇧🇿', dialCode: '+501', currency: 'BZD' },
    { name: 'Bénin', code: 'BJ', flag: '🇧🇯', dialCode: '+229', currency: 'XOF' },
    { name: 'Bermudes', code: 'BM', flag: '🇧🇲', dialCode: '+1441', currency: 'BMD' },
    { name: 'Bhoutan', code: 'BT', flag: '🇧🇹', dialCode: '+975', currency: 'BTN' },
    { name: 'Biélorussie', code: 'BY', flag: '🇧🇾', dialCode: '+375', currency: 'BYR' },
    { name: 'Bolivie', code: 'BO', flag: '🇧🇴', dialCode: '+591', currency: 'BOB' },
    { name: 'Bosnie-Herzégovine', code: 'BA', flag: '🇧🇦', dialCode: '+387', currency: 'BAM' },
    { name: 'Botswana', code: 'BW', flag: '🇧🇼', dialCode: '+267', currency: 'BWP' },
    { name: 'Brésil', code: 'BR', flag: '🇧🇷', dialCode: '+55', currency: 'BRL' },
    { name: 'Brunei', code: 'BN', flag: '🇧🇳', dialCode: '+673', currency: 'BND' },
    { name: 'Bulgarie', code: 'BG', flag: '🇧🇬', dialCode: '+359', currency: 'BGN' },
    { name: 'Burkina Faso', code: 'BF', flag: '🇧🇫', dialCode: '+226', currency: 'XOF' },
    { name: 'Burundi', code: 'BI', flag: '🇧🇮', dialCode: '+257', currency: 'BIF' },
    { name: 'Cambodge', code: 'KH', flag: '🇰🇭', dialCode: '+855', currency: 'KHR' },
    { name: 'Cameroun', code: 'CM', flag: '🇨🇲', dialCode: '+237', currency: 'XAF' },
    { name: 'Canada', code: 'CA', flag: '🇨🇦', dialCode: '+1', currency: 'CAD' },
    { name: 'Cap-Vert', code: 'CV', flag: '🇨🇻', dialCode: '+238', currency: 'CVE' },
    { name: 'Chili', code: 'CL', flag: '🇨🇱', dialCode: '+56', currency: 'CLP' },
    { name: 'Chine', code: 'CN', flag: '🇨🇳', dialCode: '+86', currency: 'CNY' },
    { name: 'Chypre', code: 'CY', flag: '🇨🇾', dialCode: '+357', currency: 'EUR' },
    { name: 'Colombie', code: 'CO', flag: '🇨🇴', dialCode: '+57', currency: 'COP' },
    { name: 'Comores', code: 'KM', flag: '🇰🇲', dialCode: '+269', currency: 'KMF' },
    { name: 'Congo-Brazzaville', code: 'CG', flag: '🇨🇬', dialCode: '+242', currency: 'XAF' },
    { name: 'Congo-Kinshasa', code: 'CD', flag: '🇨🇩', dialCode: '+243', currency: 'CDF' },
    { name: 'Corée du Nord', code: 'KP', flag: '🇰🇵', dialCode: '+850', currency: 'KPW' },
    { name: 'Corée du Sud', code: 'KR', flag: '🇰🇷', dialCode: '+82', currency: 'KRW' },
    { name: 'Costa Rica', code: 'CR', flag: '🇨🇷', dialCode: '+506', currency: 'CRC' },
    { name: 'Côte d’Ivoire', code: 'CI', flag: '🇨🇮', dialCode: '+225', currency: 'XOF' },
    { name: 'Croatie', code: 'HR', flag: '🇭🇷', dialCode: '+385', currency: 'HRK' },
    { name: 'Cuba', code: 'CU', flag: '🇨🇺', dialCode: '+53', currency: 'CUP' },
    { name: 'Danemark', code: 'DK', flag: '🇩🇰', dialCode: '+45', currency: 'DKK' },
    { name: 'Djibouti', code: 'DJ', flag: '🇩🇯', dialCode: '+253', currency: 'DJF' },
    { name: 'Dominique', code: 'DM', flag: '🇩🇲', dialCode: '+1767', currency: 'XCD' },
    { name: 'Égypte', code: 'EG', flag: '🇪🇬', dialCode: '+20', currency: 'EGP' },
    { name: 'Émirats Arabes Unis', code: 'AE', flag: '🇦🇪', dialCode: '+971', currency: 'AED' },
    { name: 'Équateur', code: 'EC', flag: '🇪🇨', dialCode: '+593', currency: 'USD' },
    { name: 'Érythrée', code: 'ER', flag: '🇪🇷', dialCode: '+291', currency: 'ERN' },
    { name: 'Espagne', code: 'ES', flag: '🇪🇸', dialCode: '+34', currency: 'EUR' },
    { name: 'Estonie', code: 'EE', flag: '🇪🇪', dialCode: '+372', currency: 'EUR' },
    { name: 'Eswatini', code: 'SZ', flag: '🇸🇿', dialCode: '+268', currency: 'SZL' },
    { name: 'États-Unis', code: 'US', flag: '🇺🇸', dialCode: '+1', currency: 'USD' },
    { name: 'Éthiopie', code: 'ET', flag: '🇪🇹', dialCode: '+251', currency: 'ETB' },
    { name: 'Fidji', code: 'FJ', flag: '🇫🇯', dialCode: '+679', currency: 'FJD' },
    { name: 'Finlande', code: 'FI', flag: '🇫🇮', dialCode: '+358', currency: 'EUR' },
    { name: 'Gabon', code: 'GA', flag: '🇬🇦', dialCode: '+241', currency: 'XAF' },
    { name: 'Gambie', code: 'GM', flag: '🇬🇲', dialCode: '+220', currency: 'GMD' },
    { name: 'Géorgie', code: 'GE', flag: '🇬🇪', dialCode: '+995', currency: 'GEL' },
    { name: 'Ghana', code: 'GH', flag: '🇬🇭', dialCode: '+233', currency: 'GHS' },
    { name: 'Gibraltar', code: 'GI', flag: '🇬🇮', dialCode: '+350', currency: 'GIP' },
    { name: 'Grèce', code: 'GR', flag: '🇬🇷', dialCode: '+30', currency: 'EUR' },
    { name: 'Grenade', code: 'GD', flag: '🇬🇩', dialCode: '+1473', currency: 'XCD' },
    { name: 'Groenland', code: 'GL', flag: '🇬🇱', dialCode: '+299', currency: 'DKK' },
    { name: 'Guadeloupe', code: 'GP', flag: '🇬🇵', dialCode: '+590', currency: 'EUR' },
    { name: 'Guam', code: 'GU', flag: '🇬🇺', dialCode: '+1671', currency: 'USD' },
    { name: 'Guatemala', code: 'GT', flag: '🇬🇹', dialCode: '+502', currency: 'GTQ' },
    { name: 'Guernesey', code: 'GG', flag: '🇬🇬', dialCode: '+44', currency: 'GGP' },
    { name: 'Guinée', code: 'GN', flag: '🇬🇳', dialCode: '+224', currency: 'GNF' },
    { name: 'Guinée-Bissau', code: 'GW', flag: '🇬🇼', dialCode: '+245', currency: 'XOF' },
    { name: 'Guinée Équatoriale', code: 'GQ', flag: '🇬🇶', dialCode: '+240', currency: 'XAF' },
    { name: 'Guyana', code: 'GY', flag: '🇬🇾', dialCode: '+592', currency: 'GYD' },
    { name: 'Guyane française', code: 'GF', flag: '🇬🇫', dialCode: '+594', currency: 'EUR' },
    { name: 'Haïti', code: 'HT', flag: '🇭🇹', dialCode: '+509', currency: 'HTG' },
    { name: 'Honduras', code: 'HN', flag: '🇭🇳', dialCode: '+504', currency: 'HNL' },
    { name: 'Hong Kong', code: 'HK', flag: '🇭🇰', dialCode: '+852', currency: 'HKD' },
    { name: 'Hongrie', code: 'HU', flag: '🇭🇺', dialCode: '+36', currency: 'HUF' },
    { name: 'Île de Man', code: 'IM', flag: '🇮🇲', dialCode: '+44', currency: 'IMP' },
    { name: 'Île Maurice', code: 'MU', flag: '🇲🇺', dialCode: '+230', currency: 'MUR' },
    { name: 'Îles Caïmans', code: 'KY', flag: '🇰🇾', dialCode: '+1345', currency: 'KYD' },
    { name: 'Îles Cook', code: 'CK', flag: '🇨🇰', dialCode: '+682', currency: 'NZD' },
    { name: 'Îles Féroé', code: 'FO', flag: '🇫🇴', dialCode: '+298', currency: 'DKK' },
    { name: 'Îles Malouines', code: 'FK', flag: '🇫🇰', dialCode: '+500', currency: 'FKP' },
    { name: 'Îles Marshall', code: 'MH', flag: '🇲🇭', dialCode: '+692', currency: 'USD' },
    { name: 'Îles Salomon', code: 'SB', flag: '🇸🇧', dialCode: '+677', currency: 'SBD' },
    { name: 'Îles Turques-et-Caïques', code: 'TC', flag: '🇹🇨', dialCode: '+1649', currency: 'USD' },
    { name: 'Îles Vierges britanniques', code: 'VG', flag: '🇻🇬', dialCode: '+1284', currency: 'USD' },
    { name: 'Îles Vierges des États-Unis', code: 'VI', flag: '🇻🇮', dialCode: '+1340', currency: 'USD' },
    { name: 'Inde', code: 'IN', flag: '🇮🇳', dialCode: '+91', currency: 'INR' },
    { name: 'Indonésie', code: 'ID', flag: '🇮🇩', dialCode: '+62', currency: 'IDR' },
    { name: 'Irak', code: 'IQ', flag: '🇮🇶', dialCode: '+964', currency: 'IQD' },
    { name: 'Iran', code: 'IR', flag: '🇮🇷', dialCode: '+98', currency: 'IRR' },
    { name: 'Irlande', code: 'IE', flag: '🇮🇪', dialCode: '+353', currency: 'EUR' },
    { name: 'Islande', code: 'IS', flag: '🇮🇸', dialCode: '+354', currency: 'ISK' },
    { name: 'Israël', code: 'IL', flag: '🇮🇱', dialCode: '+972', currency: 'ILS' },
    { name: 'Italie', code: 'IT', flag: '🇮🇹', dialCode: '+39', currency: 'EUR' },
    { name: 'Jamaïque', code: 'JM', flag: '🇯🇲', dialCode: '+1876', currency: 'JMD' },
    { name: 'Japon', code: 'JP', flag: '🇯🇵', dialCode: '+81', currency: 'JPY' },
    { name: 'Jersey', code: 'JE', flag: '🇯🇪', dialCode: '+44', currency: 'JEP' },
    { name: 'Jordanie', code: 'JO', flag: '🇯🇴', dialCode: '+962', currency: 'JOD' },
    { name: 'Kazakhstan', code: 'KZ', flag: '🇰🇿', dialCode: '+7', currency: 'KZT' },
    { name: 'Kenya', code: 'KE', flag: '🇰🇪', dialCode: '+254', currency: 'KES' },
    { name: 'Kirghizistan', code: 'KG', flag: '🇰🇬', dialCode: '+996', currency: 'KGS' },
    { name: 'Kiribati', code: 'KI', flag: '🇰🇮', dialCode: '+686', currency: 'AUD' },
    { name: 'Koweït', code: 'KW', flag: '🇰🇼', dialCode: '+965', currency: 'KWD' },
    { name: 'Laos', code: 'LA', flag: '🇱🇦', dialCode: '+856', currency: 'LAK' },
    { name: 'Lesotho', code: 'LS', flag: '🇱🇸', dialCode: '+266', currency: 'LSL' },
    { name: 'Lettonie', code: 'LV', flag: '🇱🇻', dialCode: '+371', currency: 'EUR' },
    { name: 'Liban', code: 'LB', flag: '🇱🇧', dialCode: '+961', currency: 'LBP' },
    { name: 'Libéria', code: 'LR', flag: '🇱🇷', dialCode: '+231', currency: 'LRD' },
    { name: 'Libye', code: 'LY', flag: '🇱🇾', dialCode: '+218', currency: 'LYD' },
    { name: 'Liechtenstein', code: 'LI', flag: '🇱🇮', dialCode: '+423', currency: 'CHF' },
    { name: 'Lituanie', code: 'LT', flag: '🇱🇹', dialCode: '+370', currency: 'EUR' },
    { name: 'Luxembourg', code: 'LU', flag: '🇱🇺', dialCode: '+352', currency: 'EUR' },
    { name: 'Macao', code: 'MO', flag: '🇲🇴', dialCode: '+853', currency: 'MOP' },
    { name: 'Macédoine du Nord', code: 'MK', flag: '🇲🇰', dialCode: '+389', currency: 'MKD' },
    { name: 'Madagascar', code: 'MG', flag: '🇲🇬', dialCode: '+261', currency: 'MGA' },
    { name: 'Malaisie', code: 'MY', flag: '🇲🇾', dialCode: '+60', currency: 'MYR' },
    { name: 'Malawi', code: 'MW', flag: '🇲🇼', dialCode: '+265', currency: 'MWK' },
    { name: 'Maldives', code: 'MV', flag: '🇲🇻', dialCode: '+960', currency: 'MVR' },
    { name: 'Mali', code: 'ML', flag: '🇲🇱', dialCode: '+223', currency: 'XOF' },
    { name: 'Malte', code: 'MT', flag: '🇲🇹', dialCode: '+356', currency: 'EUR' },
    { name: 'Mariannes du Nord', code: 'MP', flag: '🇲🇵', dialCode: '+1670', currency: 'USD' },
    { name: 'Maroc', code: 'MA', flag: '🇲🇦', dialCode: '+212', currency: 'MAD' },
    { name: 'Martinique', code: 'MQ', flag: '🇲🇶', dialCode: '+596', currency: 'EUR' },
    { name: 'Maurice', code: 'MU', flag: '🇲🇺', dialCode: '+230', currency: 'MUR' },
    { name: 'Mauritanie', code: 'MR', flag: '🇲🇷', dialCode: '+222', currency: 'MRU' },
    { name: 'Mayotte', code: 'YT', flag: '🇾🇹', dialCode: '+262', currency: 'EUR' },
    { name: 'Mexique', code: 'MX', flag: '🇲🇽', dialCode: '+52', currency: 'MXN' },
    { name: 'Micronésie', code: 'FM', flag: '🇫🇲', dialCode: '+691', currency: 'USD' },
    { name: 'Moldavie', code: 'MD', flag: '🇲🇩', dialCode: '+373', currency: 'MDL' },
    { name: 'Monaco', code: 'MC', flag: '🇲🇨', dialCode: '+377', currency: 'EUR' },
    { name: 'Mongolie', code: 'MN', flag: '🇲🇳', dialCode: '+976', currency: 'MNT' },
    { name: 'Monténégro', code: 'ME', flag: '🇲🇪', dialCode: '+382', currency: 'EUR' },
    { name: 'Montserrat', code: 'MS', flag: '🇲🇸', dialCode: '+1664', currency: 'XCD' },
    { name: 'Mozambique', code: 'MZ', flag: '🇲🇿', dialCode: '+258', currency: 'MZN' },
    { name: 'Myanmar', code: 'MM', flag: '🇲🇲', dialCode: '+95', currency: 'MMK' },
    { name: 'Namibie', code: 'NA', flag: '🇳🇦', dialCode: '+264', currency: 'NAD' },
    { name: 'Nauru', code: 'NR', flag: '🇳🇷', dialCode: '+674', currency: 'AUD' },
    { name: 'Népal', code: 'NP', flag: '🇳🇵', dialCode: '+977', currency: 'NPR' },
    { name: 'Nicaragua', code: 'NI', flag: '🇳🇮', dialCode: '+505', currency: 'NIO' },
    { name: 'Niger', code: 'NE', flag: '🇳🇪', dialCode: '+227', currency: 'XOF' },
    { name: 'Nigeria', code: 'NG', flag: '🇳🇬', dialCode: '+234', currency: 'NGN' },
    { name: 'Niue', code: 'NU', flag: '🇳🇺', dialCode: '+683', currency: 'NZD' },
    { name: 'Norvège', code: 'NO', flag: '🇳🇴', dialCode: '+47', currency: 'NOK' },
    { name: 'Nouvelle-Calédonie', code: 'NC', flag: '🇳🇨', dialCode: '+687', currency: 'XPF' },
    { name: 'Nouvelle-Zélande', code: 'NZ', flag: '🇳🇿', dialCode: '+64', currency: 'NZD' },
    { name: 'Oman', code: 'OM', flag: '🇴🇲', dialCode: '+968', currency: 'OMR' },
    { name: 'Ouganda', code: 'UG', flag: '🇺🇬', dialCode: '+256', currency: 'UGX' },
    { name: 'Ouzbékistan', code: 'UZ', flag: '🇺🇿', dialCode: '+998', currency: 'UZS' },
    { name: 'Pakistan', code: 'PK', flag: '🇵🇰', dialCode: '+92', currency: 'PKR' },
    { name: 'Palaos', code: 'PW', flag: '🇵🇼', dialCode: '+680', currency: 'USD' },
    { name: 'Palestine', code: 'PS', flag: '🇵🇸', dialCode: '+970', currency: 'ILS' },
    { name: 'Panama', code: 'PA', flag: '🇵🇦', dialCode: '+507', currency: 'PAB' },
    { name: 'Papouasie-Nouvelle-Guinée', code: 'PG', flag: '🇵🇬', dialCode: '+675', currency: 'PGK' },
    { name: 'Paraguay', code: 'PY', flag: '🇵🇾', dialCode: '+595', currency: 'PYG' },
    { name: 'Pays-Bas', code: 'NL', flag: '🇳🇱', dialCode: '+31', currency: 'EUR' },
    { name: 'Pérou', code: 'PE', flag: '🇵🇪', dialCode: '+51', currency: 'PEN' },
    { name: 'Philippines', code: 'PH', flag: '🇵🇭', dialCode: '+63', currency: 'PHP' },
    { name: 'Pologne', code: 'PL', flag: '🇵🇱', dialCode: '+48', currency: 'PLN' },
    { name: 'Polynésie française', code: 'PF', flag: '🇵🇫', dialCode: '+689', currency: 'XPF' },
    { name: 'Porto Rico', code: 'PR', flag: '🇵🇷', dialCode: '+1787', currency: 'USD' },
    { name: 'Portugal', code: 'PT', flag: '🇵🇹', dialCode: '+351', currency: 'EUR' },
    { name: 'Qatar', code: 'QA', flag: '🇶🇦', dialCode: '+974', currency: 'QAR' },
    { name: 'RCA', code: 'CF', flag: '🇨🇫', dialCode: '+236', currency: 'XAF' },
    { name: 'Réunion', code: 'RE', flag: '🇷🇪', dialCode: '+262', currency: 'EUR' },
    { name: 'Roumanie', code: 'RO', flag: '🇷🇴', dialCode: '+40', currency: 'RON' },
    { name: 'Royaume-Uni', code: 'GB', flag: '🇬🇧', dialCode: '+44', currency: 'GBP' },
    { name: 'Russie', code: 'RU', flag: '🇷🇺', dialCode: '+7', currency: 'RUB' },
    { name: 'Rwanda', code: 'RW', flag: '🇷🇼', dialCode: '+250', currency: 'RWF' },
    { name: 'Sahara occidental', code: 'EH', flag: '🇪🇭', dialCode: '+212', currency: 'MAD' },
    { name: 'Saint-Barthélemy', code: 'BL', flag: '🇧🇱', dialCode: '+590', currency: 'EUR' },
    { name: 'Saint-Christophe-et-Niévès', code: 'KN', flag: '🇰🇳', dialCode: '+1869', currency: 'XCD' },
    { name: 'Saint-Marin', code: 'SM', flag: '🇸🇲', dialCode: '+378', currency: 'EUR' },
    { name: 'Saint-Martin', code: 'MF', flag: '🇲🇫', dialCode: '+590', currency: 'EUR' },
    { name: 'Saint-Pierre-et-Miquelon', code: 'PM', flag: '🇵🇲', dialCode: '+508', currency: 'EUR' },
    { name: 'Saint-Vincent-et-les-Grenadines', code: 'VC', flag: '🇻🇨', dialCode: '+1784', currency: 'XCD' },
    { name: 'Sainte-Hélène', code: 'SH', flag: '🇸🇭', dialCode: '+290', currency: 'SHP' },
    { name: 'Sainte-Lucie', code: 'LC', flag: '🇱🇨', dialCode: '+1758', currency: 'XCD' },
    { name: 'Salvador', code: 'SV', flag: '🇸🇻', dialCode: '+503', currency: 'USD' },
    { name: 'Samoa', code: 'WS', flag: '🇼🇸', dialCode: '+685', currency: 'WST' },
    { name: 'Samoa américaines', code: 'AS', flag: '🇦🇸', dialCode: '+1684', currency: 'USD' },
    { name: 'Sao Tomé-et-Principe', code: 'ST', flag: '🇸🇹', dialCode: '+239', currency: 'STD' },
    { name: 'Serbie', code: 'RS', flag: '🇷🇸', dialCode: '+381', currency: 'RSD' },
    { name: 'Seychelles', code: 'SC', flag: '🇸🇨', dialCode: '+248', currency: 'SCR' },
    { name: 'Sierra Leone', code: 'SL', flag: '🇸🇱', dialCode: '+232', currency: 'SLL' },
    { name: 'Singapour', code: 'SG', flag: '🇸🇬', dialCode: '+65', currency: 'SGD' },
    { name: 'Slovaquie', code: 'SK', flag: '🇸🇰', dialCode: '+421', currency: 'EUR' },
    { name: 'Slovénie', code: 'SI', flag: '🇸🇮', dialCode: '+386', currency: 'EUR' },
    { name: 'Somalie', code: 'SO', flag: '🇸🇴', dialCode: '+252', currency: 'SOS' },
    { name: 'Soudan', code: 'SD', flag: '🇸🇩', dialCode: '+249', currency: 'SDG' },
    { name: 'Soudan du Sud', code: 'SS', flag: '🇸🇸', dialCode: '+211', currency: 'SSP' },
    { name: 'Sri Lanka', code: 'LK', flag: '🇱🇰', dialCode: '+94', currency: 'LKR' },
    { name: 'Suède', code: 'SE', flag: '🇸🇪', dialCode: '+46', currency: 'SEK' },
    { name: 'Suisse', code: 'CH', flag: '🇨🇭', dialCode: '+41', currency: 'CHF' },
    { name: 'Suriname', code: 'SR', flag: '🇸🇷', dialCode: '+597', currency: 'SRD' },
    { name: 'Syrie', code: 'SY', flag: '🇸🇾', dialCode: '+963', currency: 'SYP' },
    { name: 'Tadjikistan', code: 'TJ', flag: '🇹🇯', dialCode: '+992', currency: 'TJS' },
    { name: 'Taïwan', code: 'TW', flag: '🇹🇼', dialCode: '+886', currency: 'TWD' },
    { name: 'Tanzanie', code: 'TZ', flag: '🇹🇿', dialCode: '+255', currency: 'TZS' },
    { name: 'Tchad', code: 'TD', flag: '🇹🇩', dialCode: '+235', currency: 'XAF' },
    { name: 'Tchéquie', code: 'CZ', flag: '🇨🇿', dialCode: '+420', currency: 'CZK' },
    { name: 'Terres australes françaises', code: 'TF', flag: '🇹🇫', dialCode: '+262', currency: 'EUR' },
    { name: 'Thaïlande', code: 'TH', flag: '🇹🇭', dialCode: '+66', currency: 'THB' },
    { name: 'Timor oriental', code: 'TL', flag: '🇹🇱', dialCode: '+670', currency: 'USD' },
    { name: 'Togo', code: 'TG', flag: '🇹🇬', dialCode: '+228', currency: 'XOF' },
    { name: 'Tokelau', code: 'TK', flag: '🇹🇰', dialCode: '+690', currency: 'NZD' },
    { name: 'Tonga', code: 'TO', flag: '🇹🇴', dialCode: '+676', currency: 'TOP' },
    { name: 'Trinité-et-Tobago', code: 'TT', flag: '🇹🇹', dialCode: '+1868', currency: 'TTD' },
    { name: 'Tunisie', code: 'TN', flag: '🇹🇳', dialCode: '+216', currency: 'TND' },
    { name: 'Turkménistan', code: 'TM', flag: '🇹🇲', dialCode: '+993', currency: 'TMT' },
    { name: 'Turquie', code: 'TR', flag: '🇹🇷', dialCode: '+90', currency: 'TRY' },
    { name: 'Tuvalu', code: 'TV', flag: '🇹🇻', dialCode: '+688', currency: 'AUD' },
    { name: 'Ukraine', code: 'UA', flag: '🇺🇦', dialCode: '+380', currency: 'UAH' },
    { name: 'Uruguay', code: 'UY', flag: '🇺🇾', dialCode: '+598', currency: 'UYU' },
    { name: 'Vanuatu', code: 'VU', flag: '🇻🇺', dialCode: '+678', currency: 'VUV' },
    { name: 'Vatican', code: 'VA', flag: '🇻🇦', dialCode: '+39', currency: 'EUR' },
    { name: 'Venezuela', code: 'VE', flag: '🇻🇪', dialCode: '+58', currency: 'VEF' },
    { name: 'Viêt Nam', code: 'VN', flag: '🇻🇳', dialCode: '+84', currency: 'VND' },
    { name: 'Wallis-et-Futuna', code: 'WF', flag: '🇼🇫', dialCode: '+681', currency: 'XPF' },
    { name: 'Yémen', code: 'YE', flag: '🇾🇪', dialCode: '+967', currency: 'YER' },
    { name: 'Zambie', code: 'ZM', flag: '🇿🇲', dialCode: '+260', currency: 'ZMK' },
    { name: 'Zimbabwe', code: 'ZW', flag: '🇿🇼', dialCode: '+263', currency: 'ZWL' },
];
