import { Ionicons } from '@expo/vector-icons';

export type HelpFeature = {
  icon: keyof typeof Ionicons.glyphMap;
  title: string;
  description: string;
};

export type HelpModule = {
  key: string;
  title: string;
  icon: keyof typeof Ionicons.glyphMap;
  color: string;
  guideKey: string;
  features: HelpFeature[];
  role: 'shopkeeper' | 'supplier' | 'all';
  audience?: 'default' | 'restaurant' | 'all';
};

export type FAQItem = {
  question: string;
  answer: string;
  audience?: 'default' | 'restaurant' | 'all';
};

export const HELP_MODULES: HelpModule[] = [
  {
    key: 'dashboard',
    title: 'help.modules.dashboard.title',
    icon: 'grid-outline',
    color: '#6366f1',
    guideKey: 'dashboard',
    role: 'shopkeeper',
    audience: 'default',
    features: [
      { icon: 'trending-up-outline', title: 'help.modules.dashboard.f1.t', description: "help.modules.dashboard.f1.d" },
      { icon: 'pie-chart-outline', title: 'help.modules.dashboard.f2.t', description: "help.modules.dashboard.f2.d" },
      { icon: 'alert-circle-outline', title: 'help.modules.dashboard.f3.t', description: "help.modules.dashboard.f3.d" },
      { icon: 'repeat-outline', title: 'help.modules.dashboard.f4.t', description: "help.modules.dashboard.f4.d" },
      { icon: 'analytics-outline', title: 'help.modules.dashboard.f5.t', description: "help.modules.dashboard.f5.d" },
      { icon: 'bar-chart-outline', title: 'help.modules.dashboard.f6.t', description: "help.modules.dashboard.f6.d" },
      { icon: 'options-outline', title: 'help.modules.dashboard.f7.t', description: "help.modules.dashboard.f7.d" },
      { icon: 'share-outline', title: 'help.modules.dashboard.f8.t', description: "help.modules.dashboard.f8.d" },
      { icon: 'information-circle-outline', title: 'help.modules.dashboard.f9.t', description: "help.modules.dashboard.f9.d" },
    ],
  },
  {
    key: 'products',
    title: 'help.modules.products.title',
    icon: 'cube-outline',
    color: '#10b981',
    guideKey: 'products',
    role: 'shopkeeper',
    audience: 'default',
    features: [
      { icon: 'search-outline', title: 'help.modules.products.f1.t', description: "help.modules.products.f1.d" },
      { icon: 'pricetag-outline', title: 'help.modules.products.f2.t', description: "help.modules.products.f2.d" },
      { icon: 'swap-vertical-outline', title: 'help.modules.products.f3.t', description: "help.modules.products.f3.d" },
      { icon: 'qr-code-outline', title: 'help.modules.products.f4.t', description: "help.modules.products.f4.d" },
      { icon: 'settings-outline', title: 'help.modules.products.f5.t', description: "help.modules.products.f5.d" },
      { icon: 'layers-outline', title: 'help.modules.products.f6.t', description: "help.modules.products.f6.d" },
      { icon: 'trending-up-outline', title: 'help.modules.products.f7.t', description: "help.modules.products.f7.d" },
      { icon: 'cloud-upload-outline', title: 'help.modules.products.f8.t', description: "help.modules.products.f8.d" },
      { icon: 'scan-outline', title: 'help.modules.products.f9.t', description: "help.modules.products.f9.d" },
      { icon: 'download-outline', title: 'help.modules.products.f10.t', description: "help.modules.products.f10.d" },
      { icon: 'arrow-undo-outline', title: 'help.modules.products.f11.t', description: "help.modules.products.f11.d" },
    ],
  },
  {
    key: 'locations',
    title: "Emplacements de stockage",
    icon: 'map-outline',
    color: '#0ea5e9',
    guideKey: 'locations',
    role: 'shopkeeper',
    audience: 'default',
    features: [
      { icon: 'albums-outline', title: "Construire votre structure", description: "Créez une organisation claire avec vos propres mots : zone, allée, rayon, niveau, étagère ou tout autre repère utile à votre activité." },
      { icon: 'layers-outline', title: "Génération guidée", description: "Créez plusieurs emplacements d'un coup au lieu de les saisir un par un, puis relisez l'aperçu avant validation." },
      { icon: 'cube-outline', title: "Affectation des produits", description: "Associez ensuite chaque produit au bon emplacement pour accélérer le rangement, l'inventaire et la recherche d'un article." },
      { icon: 'swap-horizontal-outline', title: "Évolution de la structure", description: "Corrigez, archivez, réactivez ou modifiez les emplacements quand l'organisation du stock change." },
    ],
  },
  {
    key: 'pos',
    title: 'help.modules.pos.title',
    icon: 'calculator-outline',
    color: '#f59e0b',
    guideKey: 'pos',
    role: 'shopkeeper',
    audience: 'default',
    features: [
      { icon: 'barcode-outline', title: 'help.modules.pos.f1.t', description: "help.modules.pos.f1.d" },
      { icon: 'cart-outline', title: 'help.modules.pos.f2.t', description: "help.modules.pos.f2.d" },
      { icon: 'person-outline', title: 'help.modules.pos.f3.t', description: "help.modules.pos.f3.d" },
      { icon: 'card-outline', title: 'help.modules.pos.f4.t', description: "help.modules.pos.f4.d" },
      { icon: 'receipt-outline', title: 'help.modules.pos.f5.t', description: "help.modules.pos.f5.d" },
      { icon: 'ribbon-outline', title: 'help.modules.pos.f6.t', description: "help.modules.pos.f6.d" },
      { icon: 'layers-outline', title: 'help.modules.pos.f7.t', description: "help.modules.pos.f7.d" },
      { icon: 'pricetag-outline', title: 'help.modules.pos.f8.t', description: "help.modules.pos.f8.d" },
      { icon: 'calculator-outline', title: 'help.modules.pos.f9.t', description: "help.modules.pos.f9.d" },
      { icon: 'share-outline', title: 'help.modules.pos.f10.t', description: "help.modules.pos.f10.d" },
    ],
  },
  {
    key: 'orders',
    title: 'help.modules.orders.title',
    icon: 'document-text-outline',
    color: '#3b82f6',
    guideKey: 'orders',
    role: 'shopkeeper',
    audience: 'default',
    features: [
      { icon: 'add-circle-outline', title: 'help.modules.orders.f1.t', description: "help.modules.orders.f1.d" },
      { icon: 'navigate-outline', title: 'help.modules.orders.f2.t', description: "help.modules.orders.f2.d" },
      { icon: 'sparkles-outline', title: 'help.modules.orders.f3.t', description: "help.modules.orders.f3.d" },
      { icon: 'link-outline', title: 'help.modules.orders.f4.t', description: "help.modules.orders.f4.d" },
      { icon: 'filter-outline', title: 'help.modules.orders.f5.t', description: "help.modules.orders.f5.d" },
      { icon: 'checkbox-outline', title: 'help.modules.orders.f6.t', description: "help.modules.orders.f6.d" },
      { icon: 'arrow-undo-outline', title: 'help.modules.orders.f7.t', description: "help.modules.orders.f7.d" },
      { icon: 'star-outline', title: 'help.modules.orders.f8.t', description: "help.modules.orders.f8.d" },
      { icon: 'camera-outline', title: 'help.modules.orders.f9.t', description: "help.modules.orders.f9.d" },
    ],
  },
  {
    key: 'suppliers',
    title: 'help.modules.suppliers.title',
    icon: 'people-outline',
    color: '#8b5cf6',
    guideKey: 'suppliers',
    role: 'shopkeeper',
    audience: 'default',
    features: [
      { icon: 'person-add-outline', title: 'help.modules.suppliers.f1.t', description: "help.modules.suppliers.f1.d" },
      { icon: 'call-outline', title: 'help.modules.suppliers.f2.t', description: "help.modules.suppliers.f2.d" },
      { icon: 'globe-outline', title: 'help.modules.suppliers.f3.t', description: "help.modules.suppliers.f3.d" },
      { icon: 'link-outline', title: 'help.modules.suppliers.f4.t', description: "help.modules.suppliers.f4.d" },
      { icon: 'chatbubble-outline', title: 'help.modules.suppliers.f5.t', description: "help.modules.suppliers.f5.d" },
      { icon: 'arrow-up-circle-outline', title: 'help.modules.suppliers.f6.t', description: "help.modules.suppliers.f6.d" },
      { icon: 'document-text-outline', title: 'help.modules.suppliers.f7.t', description: "help.modules.suppliers.f7.d" },
      { icon: 'journal-outline', title: 'help.modules.suppliers.f8.t', description: "help.modules.suppliers.f8.d" },
    ],
  },
  {
    key: 'crm',
    title: 'help.modules.crm.title',
    icon: 'heart-outline',
    color: '#ec4899',
    guideKey: 'crm',
    role: 'shopkeeper',
    audience: 'default',
    features: [
      { icon: 'people-outline', title: 'help.modules.crm.f1.t', description: "help.modules.crm.f1.d" },
      { icon: 'ribbon-outline', title: 'help.modules.crm.f2.t', description: "help.modules.crm.f2.d" },
      { icon: 'wallet-outline', title: 'help.modules.crm.f3.t', description: "help.modules.crm.f3.d" },
      { icon: 'megaphone-outline', title: 'help.modules.crm.f4.t', description: "help.modules.crm.f4.d" },
      { icon: 'gift-outline', title: 'help.modules.crm.f5.t', description: "help.modules.crm.f5.d" },
      { icon: 'calendar-outline', title: 'help.modules.crm.f6.t', description: "help.modules.crm.f6.d" },
      { icon: 'call-outline', title: 'help.modules.crm.f7.t', description: "help.modules.crm.f7.d" },
      { icon: 'download-outline', title: 'help.modules.crm.f8.t', description: "help.modules.crm.f8.d" },
    ],
  },
  {
    key: 'accounting',
    title: 'help.modules.accounting.title',
    icon: 'calculator-outline',
    color: '#14b8a6',
    guideKey: 'accounting',
    role: 'shopkeeper',
    audience: 'all',
    features: [
      { icon: 'calendar-outline', title: 'help.modules.accounting.f1.t', description: "help.modules.accounting.f1.d" },
      { icon: 'stats-chart-outline', title: 'help.modules.accounting.f2.t', description: "help.modules.accounting.f2.d" },
      { icon: 'document-text-outline', title: 'help.modules.accounting.f3.t', description: "help.modules.accounting.f3.d" },
      { icon: 'cash-outline', title: 'help.modules.accounting.f4.t', description: "help.modules.accounting.f4.d" },
      { icon: 'pie-chart-outline', title: 'help.modules.accounting.f5.t', description: "help.modules.accounting.f5.d" },
      { icon: 'download-outline', title: 'help.modules.accounting.f6.t', description: "help.modules.accounting.f6.d" },
      { icon: 'trophy-outline', title: 'help.modules.accounting.f7.t', description: "help.modules.accounting.f7.d" },
      { icon: 'information-circle-outline', title: 'help.modules.accounting.f8.t', description: "help.modules.accounting.f8.d" },
    ],
  },
  {
    key: 'alerts',
    title: 'help.modules.alerts.title',
    icon: 'notifications-outline',
    color: '#ef4444',
    guideKey: 'alerts',
    role: 'shopkeeper',
    audience: 'default',
    features: [
      { icon: 'settings-outline', title: 'help.modules.alerts.f1.t', description: "help.modules.alerts.f1.d" },
      { icon: 'flash-outline', title: 'help.modules.alerts.f2.t', description: "help.modules.alerts.f2.d" },
      { icon: 'bed-outline', title: 'help.modules.alerts.f3.t', description: "help.modules.alerts.f3.d" },
      { icon: 'checkmark-done-outline', title: 'help.modules.alerts.f4.t', description: "help.modules.alerts.f4.d" },
      { icon: 'sparkles-outline', title: 'help.modules.alerts.f5.t', description: "help.modules.alerts.f5.d" },
      { icon: 'notifications-outline', title: 'help.modules.alerts.f6.t', description: "Compteur dans l'en-tete, notifications push et ouverture directe vers l'ecran Alertes quand une notification compatible est touchee." },
    ],
  },
  {
    key: 'activity',
    title: "help.modules.activity.title",
    icon: 'time-outline',
    color: '#64748b',
    guideKey: 'activity',
    role: 'shopkeeper',
    audience: 'all',
    features: [
      { icon: 'list-outline', title: 'help.modules.activity.f1.t', description: "help.modules.activity.f1.d" },
      { icon: 'funnel-outline', title: 'help.modules.activity.f2.t', description: "help.modules.activity.f2.d" },
      { icon: 'people-outline', title: 'help.modules.activity.f3.t', description: "help.modules.activity.f3.d" },
      { icon: 'download-outline', title: "Exporter le journal", description: "Exportez l'historique lorsque vous devez partager une vérification, archiver une période ou relire les événements dans un tableur ou un PDF." },
      { icon: 'business-outline', title: "Conserver le bon contexte", description: "Sur un compte multi-boutiques, relisez toujours l'historique avec la bonne boutique active pour interpréter correctement une action." },
    ],
  },
  {
    key: 'users',
    title: 'help.modules.users.title',
    icon: 'shield-outline',
    color: '#f97316',
    guideKey: 'users',
    role: 'shopkeeper',
    audience: 'all',
    features: [
      { icon: 'person-add-outline', title: 'help.modules.users.f1.t', description: "help.modules.users.f1.d" },
      { icon: 'lock-closed-outline', title: 'help.modules.users.f2.t', description: "help.modules.users.f2.d" },
      { icon: 'key-outline', title: 'help.modules.users.f3.t', description: "help.modules.users.f3.d" },
      { icon: 'trash-outline', title: 'help.modules.users.f4.t', description: "help.modules.users.f4.d" },
      { icon: 'business-outline', title: 'help.modules.users.f5.t', description: "help.modules.users.f5.d" },
      { icon: 'share-social-outline', title: 'help.modules.users.f6.t', description: "help.modules.users.f6.d" },
    ],
  },
  {
    key: 'settings',
    title: 'help.modules.settings.title',
    icon: 'settings-outline',
    color: '#6366f1',
    guideKey: 'settings',
    role: 'all',
    audience: 'all',
    features: [
      { icon: 'person-outline', title: "Compte et application", description: "Réglez ici l'apparence, la langue, les préférences de compte, l'abonnement et les options liées à votre appareil." },
      { icon: 'storefront-outline', title: "Boutique active", description: "Retrouvez le nom, les documents et les informations du point de vente actuellement sélectionné." },
      { icon: 'business-outline', title: "Organisation et pilotage", description: "Cette rubrique regroupe l'équipe, les modules visibles et les réglages de gestion avancés." },
      { icon: 'notifications-outline', title: "Alertes et rappels", description: "Choisissez les canaux d'alerte, les destinataires utiles, les seuils et lancez une notification de test pour verifier le branchement push." },
      { icon: 'card-outline', title: "Abonnement et facturation", description: "Consultez votre formule actuelle, comparez les autres offres et relisez les réglages liés au renouvellement." },
      { icon: 'sync-outline', title: "Synchronisation", description: "Vérifiez l'état de connexion, les actions en attente et les commandes de synchronisation." },
      { icon: 'help-circle-outline', title: "Support et incidents", description: "Le centre d'aide, l'assistant et le contact support sont regroupés au même endroit." },
      { icon: 'warning-outline', title: "Déclarer un incident", description: "Utilisez ce formulaire quand vous devez remonter un incident ou une anomalie importante." },
      { icon: 'lock-closed-outline', title: "Sécurité et données", description: "Le code PIN, la biométrie, l'export et la suppression du compte sont dans cette zone sensible. Après une déconnexion, la reconnexion biométrique reste disponible si elle est activée." },
      { icon: 'help-circle-outline', title: "Centre d'aide", description: "Retrouvez ici les guides embarqués et les accès utiles quand vous avez besoin d'être accompagné dans l'application." },
    ],
  },
  {
    key: 'subscription',
    title: 'help.modules.subscription.title',
    icon: 'diamond-outline',
    color: '#a855f7',
    guideKey: 'subscription',
    role: 'all',
    audience: 'all',
    features: [
      { icon: 'card-outline', title: 'help.modules.subscription.f1.t', description: "help.modules.subscription.f1.d" },
      { icon: 'swap-horizontal-outline', title: 'help.modules.subscription.f2.t', description: "help.modules.subscription.f2.d" },
      { icon: 'phone-portrait-outline', title: 'help.modules.subscription.f3.t', description: "help.modules.subscription.f3.d" },
      { icon: 'refresh-outline', title: 'help.modules.subscription.f4.t', description: "help.modules.subscription.f4.d" },
      { icon: 'mail-outline', title: "Rappels avant échéance", description: "Consultez cet écran pour comprendre les rappels envoyés avant la fin de période et éviter une interruption d'accès." },
      { icon: 'shield-checkmark-outline', title: "Conditions et confidentialité", description: "Depuis cet écran, relisez les conditions d'utilisation et la politique de confidentialité avant tout achat ou changement de formule." },
      { icon: 'person-circle-outline', title: "Contact de facturation", description: "Vérifiez la personne et l'adresse e-mail qui doivent recevoir les informations de facturation et de renouvellement." },
      { icon: 'sparkles-outline', title: "Fonctions IA selon le plan", description: "Certaines fonctions IA dépendent de votre formule. Le résumé quotidien reste limité à une fois par jour, tandis que des fonctions comme la détection d'anomalies, la suggestion de prix ou la génération de description dépendent du plan actif." },
    ],
  },
  // ============ SUPPLIER ============
  {
    key: 'supplierDashboard',
    title: 'help.modules.supplierDashboard.title',
    icon: 'stats-chart-outline',
    color: '#6366f1',
    guideKey: 'supplierDashboard',
    role: 'supplier',
    audience: 'all',
    features: [
      { icon: 'trending-up-outline', title: 'help.modules.supplierDashboard.f1.t', description: "help.modules.supplierDashboard.f1.d" },
      { icon: 'star-outline', title: 'help.modules.supplierDashboard.f2.t', description: "help.modules.supplierDashboard.f2.d" },
      { icon: 'trophy-outline', title: 'help.modules.supplierDashboard.f3.t', description: "help.modules.supplierDashboard.f3.d" },
      { icon: 'people-outline', title: 'help.modules.supplierDashboard.f4.t', description: "help.modules.supplierDashboard.f4.d" },
      { icon: 'receipt-outline', title: 'help.modules.supplierDashboard.f5.t', description: "help.modules.supplierDashboard.f5.d" },
    ],
  },
  {
    key: 'supplierCatalog',
    title: 'help.modules.supplierCatalog.title',
    icon: 'cube-outline',
    color: '#10b981',
    guideKey: 'supplierCatalog',
    role: 'supplier',
    audience: 'all',
    features: [
      { icon: 'add-circle-outline', title: 'help.modules.supplierCatalog.f1.t', description: "help.modules.supplierCatalog.f1.d" },
      { icon: 'pricetag-outline', title: 'help.modules.supplierCatalog.f2.t', description: "help.modules.supplierCatalog.f2.d" },
      { icon: 'toggle-outline', title: 'help.modules.supplierCatalog.f3.t', description: "help.modules.supplierCatalog.f3.d" },
      { icon: 'grid-outline', title: 'help.modules.supplierCatalog.f4.t', description: "help.modules.supplierCatalog.f4.d" },
    ],
  },
  {
    key: 'supplierOrders',
    title: 'help.modules.supplierOrders.title',
    icon: 'document-text-outline',
    color: '#3b82f6',
    guideKey: 'supplierOrders',
    role: 'supplier',
    audience: 'all',
    features: [
      { icon: 'list-outline', title: 'help.modules.supplierOrders.f1.t', description: "help.modules.supplierOrders.f1.d" },
      { icon: 'checkmark-circle-outline', title: 'help.modules.supplierOrders.f2.t', description: "help.modules.supplierOrders.f2.d" },
      { icon: 'airplane-outline', title: 'help.modules.supplierOrders.f3.t', description: "help.modules.supplierOrders.f3.d" },
      { icon: 'funnel-outline', title: 'help.modules.supplierOrders.f4.t', description: "help.modules.supplierOrders.f4.d" },
    ],
  },
  // ============ RESTAURANT ============
  {
    key: 'restaurantHub',
    title: 'help.modules.restaurantHub.title',
    icon: 'restaurant-outline',
    color: '#f97316',
    guideKey: 'restaurantHub',
    role: 'shopkeeper',
    audience: 'restaurant',
    features: [
      { icon: 'restaurant-outline', title: 'help.modules.restaurantHub.f1.t', description: "help.modules.restaurantHub.f1.d" },
      { icon: 'calculator-outline', title: 'help.modules.restaurantHub.f2.t', description: "help.modules.restaurantHub.f2.d" },
      { icon: 'grid-outline', title: 'help.modules.restaurantHub.f3.t', description: "help.modules.restaurantHub.f3.d" },
      { icon: 'calendar-outline', title: 'help.modules.restaurantHub.f4.t', description: "help.modules.restaurantHub.f4.d" },
    ],
  },
  {
    key: 'restaurantMenu',
    title: 'help.modules.restaurantMenu.title',
    icon: 'book-outline',
    color: '#10b981',
    guideKey: 'restaurantProducts',
    role: 'shopkeeper',
    audience: 'restaurant',
    features: [
      { icon: 'add-circle-outline', title: 'help.modules.restaurantMenu.f1.t', description: "help.modules.restaurantMenu.f1.d" },
      { icon: 'flask-outline', title: 'help.modules.restaurantMenu.f2.t', description: "help.modules.restaurantMenu.f2.d" },
      { icon: 'layers-outline', title: 'help.modules.restaurantMenu.f3.t', description: "help.modules.restaurantMenu.f3.d" },
      { icon: 'time-outline', title: 'help.modules.restaurantMenu.f4.t', description: "help.modules.restaurantMenu.f4.d" },
    ],
  },
  {
    key: 'restaurantPos',
    title: 'help.modules.restaurantPos.title',
    icon: 'calculator-outline',
    color: '#f59e0b',
    guideKey: 'restaurantPos',
    role: 'shopkeeper',
    audience: 'restaurant',
    features: [
      { icon: 'grid-outline', title: 'help.modules.restaurantPos.f1.t', description: "help.modules.restaurantPos.f1.d" },
      { icon: 'restaurant-outline', title: 'help.modules.restaurantPos.f2.t', description: "help.modules.restaurantPos.f2.d" },
      { icon: 'send-outline', title: 'help.modules.restaurantPos.f3.t', description: "help.modules.restaurantPos.f3.d" },
      { icon: 'cash-outline', title: 'help.modules.restaurantPos.f4.t', description: "help.modules.restaurantPos.f4.d" },
    ],
  },
  {
    key: 'restaurantTables',
    title: 'help.modules.restaurantTables.title',
    icon: 'grid-outline',
    color: '#3b82f6',
    guideKey: 'restaurantTables',
    role: 'shopkeeper',
    audience: 'restaurant',
    features: [
      { icon: 'ellipse-outline', title: 'help.modules.restaurantTables.f1.t', description: "help.modules.restaurantTables.f1.d" },
      { icon: 'people-outline', title: 'help.modules.restaurantTables.f2.t', description: "help.modules.restaurantTables.f2.d" },
      { icon: 'checkmark-done-outline', title: 'help.modules.restaurantTables.f3.t', description: "help.modules.restaurantTables.f3.d" },
    ],
  },
  {
    key: 'restaurantReservations',
    title: 'help.modules.restaurantReservations.title',
    icon: 'calendar-outline',
    color: '#8b5cf6',
    guideKey: 'restaurantReservations',
    role: 'shopkeeper',
    audience: 'restaurant',
    features: [
      { icon: 'add-circle-outline', title: 'help.modules.restaurantReservations.f1.t', description: "help.modules.restaurantReservations.f1.d" },
      { icon: 'time-outline', title: 'help.modules.restaurantReservations.f2.t', description: "help.modules.restaurantReservations.f2.d" },
      { icon: 'swap-horizontal-outline', title: 'help.modules.restaurantReservations.f3.t', description: "help.modules.restaurantReservations.f3.d" },
    ],
  },
  {
    key: 'restaurantKitchen',
    title: 'help.modules.restaurantKitchen.title',
    icon: 'flame-outline',
    color: '#ef4444',
    guideKey: 'restaurantKitchen',
    role: 'shopkeeper',
    audience: 'restaurant',
    features: [
      { icon: 'receipt-outline', title: 'help.modules.restaurantKitchen.f1.t', description: "help.modules.restaurantKitchen.f1.d" },
      { icon: 'checkmark-circle-outline', title: 'help.modules.restaurantKitchen.f2.t', description: "help.modules.restaurantKitchen.f2.d" },
      { icon: 'walk-outline', title: 'help.modules.restaurantKitchen.f3.t', description: "help.modules.restaurantKitchen.f3.d" },
    ],
  },
];

export const FAQ: FAQItem[] = [
  { question: 'help.faq.q1.q', answer: "help.faq.q1.a" },
  { question: 'help.faq.q2.q', answer: "help.faq.q2.a" },
  { question: 'help.faq.q3.q', answer: "help.faq.q3.a" },
  { question: 'help.faq.q4.q', answer: "help.faq.q4.a" },
  { question: 'help.faq.q5.q', answer: "help.faq.q5.a" },
  { question: 'help.faq.q6.q', answer: "help.faq.q6.a" },
  { question: 'help.faq.q7.q', answer: "help.faq.q7.a" },
  { question: 'help.faq.q8.q', answer: "help.faq.q8.a" },
  { question: 'help.faq.q9.q', answer: "help.faq.q9.a" },
  { question: 'help.faq.q10.q', answer: "help.faq.q10.a" },
  { question: 'help.faq.q11.q', answer: "help.faq.q11.a" },
  { question: 'help.faq.q12.q', answer: "help.faq.q12.a", audience: 'default' },
  { question: 'help.faq.q13.q', answer: "help.faq.q13.a", audience: 'restaurant' },
  { question: 'help.faq.q14.q', answer: "help.faq.q14.a", audience: 'restaurant' },
  { question: 'help.faq.q15.q', answer: "help.faq.q15.a", audience: 'restaurant' },
  { question: 'help.faq.q16.q', answer: "help.faq.q16.a", audience: 'restaurant' },
  { question: 'help.faq.q17.q', answer: "help.faq.q17.a", audience: 'restaurant' },
  { question: 'help.faq.q18.q', answer: "help.faq.q18.a", audience: 'restaurant' },
  { question: 'help.faq.q19.q', answer: "help.faq.q19.a" },
  { question: 'help.faq.q20.q', answer: "help.faq.q20.a" },
  { question: 'help.faq.q21.q', answer: "help.faq.q21.a" },
  { question: 'help.faq.q22.q', answer: "help.faq.q22.a" },
];

